### ISSUE TITLE
issue when loading the dpo project 

### ISSUE THREAD

**Issue by dmarcicLIH** [hisystems/DatabaseObjectsVB6#2]
Hi Toby, 
I try to check your Library with VB6 but when i load the dpo project, i have got class that could not be loaded specially the 6 class with  Expression : 

-  SQLArithmeticexpression
- SQlExpression
- SQLBitwiseExpression
- SQLFiledExpression
- SQLValueExpression
- SQLComparisonExpression

the is no problem for the rest of the class, do you have any idea? 
thanks
David

**Comment by tobywicksworkfacta** [comment]
Hi @novitito

Have a look here that should give you some examples: 
https://github.com/hisystems/DatabaseObjectsVB6-UnitTests/blob/master/SqlExpressionsTests.cls

I hope that helps.

**Comment by dmarcicLIH** [comment]
I had to recreate these 6 empty files and copy/paste the content, then it was ok. Maybe due to some end of line encoding... ?
